services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
  postgres-old:
    container_name: postgres-old
    image: postgres:16-alpine
    ports:
      - 54321:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data:/data
    command: |
      postgres
      -c log_statement=all
      -c wal_level=logical
    restart: always
  postgres-new:
    container_name: postgres-new
    image: postgres:18-alpine
    ports:
      - 54322:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    command: |
      postgres
      -c log_statement=all
      -c wal_level=logical
    restart: always
